/**
 * exportUtils.js
 * Handles generating and downloading PDFs (via print-to-pdf) and DOC (MS Word HTML) formats.
 */

// A helper to trigger the browser's download dialog for a file blob
export function downloadBlob(blob, filename) {
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  a.style.display = "none";
  document.body.appendChild(a);
  a.click();
  setTimeout(() => {
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  }, 150);
}

// Generate Word Document (.doc) from notes blocks
export function exportToWord(notes, title = "Study Guide") {
  let html = `
    <html xmlns:o="urn:schemas-microsoft-com:office:office" xmlns:w="urn:schemas-microsoft-com:office:word" xmlns="http://www.w3.org/TR/REC-html40">
    <head>
      <meta charset="utf-8">
      <title>${title}</title>
      <style>
        body { font-family: 'Segoe UI', Arial, sans-serif; line-height: 1.6; color: #333; margin: 40px; }
        h1 { font-family: 'Georgia', serif; font-size: 24pt; color: #111; border-bottom: 2px solid #333; padding-bottom: 6px; }
        h2 { font-family: 'Georgia', serif; font-size: 18pt; color: #1a1a1a; margin-top: 24pt; border-bottom: 1px solid #ddd; padding-bottom: 4px; }
        .tag { font-size: 9pt; font-weight: bold; text-transform: uppercase; color: #666; margin-bottom: 4px; }
        .bullet-list { margin-bottom: 16pt; }
        .bullet-item { margin-bottom: 6pt; }
        .term { font-weight: bold; color: #3b82f6; }
        .box { border: 1px solid #ccc; border-left: 4px solid #10b981; padding: 12px; margin-bottom: 16pt; background-color: #f9f9f9; }
        .definition-term { font-weight: bold; font-size: 12pt; color: #10b981; margin-bottom: 4px; }
        .example-box { border: 1px solid #ccc; padding: 12px; margin-bottom: 16pt; background-color: #f0f4f8; border-left: 4px solid #3b82f6; }
        .alert-box { border: 2px dashed #ef4444; padding: 12px; margin-bottom: 16pt; background-color: #fdf2f2; }
        .alert-title { font-weight: bold; color: #ef4444; }
        .highlight-box { border: 2px dashed #ef4444; padding: 12px; margin-bottom: 16pt; background-color: #fffafb; }
        .grid-container { width: 100%; border-collapse: collapse; margin-bottom: 16pt; }
        .grid-cell { border: 1px solid #ddd; padding: 12px; vertical-align: top; width: 50%; }
        .grid-title { font-weight: bold; text-transform: uppercase; font-size: 10pt; }
        .note { border-left: 3px solid #8b5cf6; padding-left: 12px; font-style: italic; color: #555; }
        .flowchart-node { border: 1px solid #1a1a1a; padding: 8px; margin: 4px; display: inline-block; border-radius: 4px; }
      </style>
    </head>
    <body>
      <h1>${title}</h1>
      <p style="color: #888; font-size: 10pt; margin-bottom: 24pt;">Generated by NotedIQ on ${new Date().toLocaleDateString()}</p>
  `;

  notes.forEach((block) => {
    switch (block.type) {
      case "banner-title":
        html += `<h2 style="text-align: center; font-style: italic;">${block.content}</h2>`;
        break;
      case "bullet-list":
        html += `<div class="bullet-list">`;
        if (block.heading) html += `<div class="tag">List: ${block.heading}</div>`;
        html += `<ul>`;
        (block.items || []).forEach((item) => {
          html += `<li class="bullet-item"><span class="term">${item.term}</span>: ${item.note}</li>`;
        });
        html += `</ul></div>`;
        break;
      case "definition": {
        const content = block.content || "";
        const colonIdx = content.indexOf(":");
        const term = colonIdx > -1 ? content.slice(0, colonIdx).trim() : "Definition";
        const body = colonIdx > -1 ? content.slice(colonIdx + 1).trim() : content;
        html += `
          <div class="box">
            <div class="definition-term">${term}</div>
            <div>${body}</div>
          </div>
        `;
        break;
      }
      case "example":
        html += `
          <div class="example-box">
            <div class="tag" style="color: #3b82f6;">Example</div>
            <div>${block.content}</div>
          </div>
        `;
        break;
      case "highlight-box":
        html += `
          <div class="highlight-box">
            <div class="alert-title">${block.term || "Important Info"}</div>
            <div>${block.content}</div>
          </div>
        `;
        break;
      case "exam-alert":
        html += `
          <div class="alert-box">
            <div class="alert-title">⚠ EXAM ALERT</div>
            <div>${block.content}</div>
          </div>
        `;
        break;
      case "riddle": {
        const content = block.content || "";
        const match = content.match(/\[Answer:\s*(.*?)\]/i);
        const answer = match ? match[1].trim() : null;
        const question = answer ? content.replace(/\[Answer:.*?\]/gi, "").trim() : content;
        html += `
          <div class="box" style="border-left-color: #f59e0b;">
            <div class="tag" style="color: #f59e0b;">Think About It / Riddle</div>
            <div>${question}</div>
          </div>
        `;
        break;
      }
      case "note":
        html += `
          <div class="note">
            <div class="tag" style="color: #8b5cf6;">Note</div>
            <div>${block.content}</div>
          </div>
        `;
        break;
      case "decision":
        html += `
          <div class="box" style="border-left-color: #94a3b8; background-color: #fbfbfb;">
            <div class="tag" style="color: #475569;">Decision</div>
            <div>${block.content}</div>
          </div>
        `;
        break;
      case "task-item":
        html += `
          <div style="margin-bottom: 8pt; padding-left: 6px;">
            <input type="checkbox" ${block.checked ? "checked" : ""}> 
            <strong>${block.content}</strong> 
            <span style="font-size: 9pt; color: #666; margin-left: 8px;">(@${block.assignee || "unassigned"} | Priority: ${block.priority || "medium"} | Due: ${block.deadline || "TBD"})</span>
          </div>
        `;
        break;
      case "structure-grid":
        html += `<div class="tag">Comparison: ${block.heading || "Grid"}</div>`;
        html += `<table class="grid-container">`;
        const items = block.items || [];
        for (let i = 0; i < items.length; i += 2) {
          html += `<tr>`;
          // cell 1
          if (items[i]) {
            html += `
              <td class="grid-cell">
                <div class="grid-title" style="color: #10b981;">${items[i].label}</div>
                <div>${Array.isArray(items[i].points) ? items[i].points.join(", ") : items[i].points}</div>
              </td>
            `;
          } else {
            html += `<td class="grid-cell"></td>`;
          }
          // cell 2
          if (items[i+1]) {
            html += `
              <td class="grid-cell">
                <div class="grid-title" style="color: #3b82f6;">${items[i+1].label}</div>
                <div>${Array.isArray(items[i+1].points) ? items[i+1].points.join(", ") : items[i+1].points}</div>
              </td>
            `;
          } else {
            html += `<td class="grid-cell"></td>`;
          }
          html += `</tr>`;
        }
        html += `</table>`;
        break;
      case "flowchart":
        html += `
          <div style="border: 1px solid #ccc; padding: 12px; margin-bottom: 16pt; background-color: #fafafa;">
            <div class="tag">Flowchart: ${block.heading || "Process"}</div>
            <div style="text-align: center; margin-top: 10px;">
        `;
        (block.nodes || []).forEach((n, idx) => {
          html += `<div class="flowchart-node">${n.label}</div>`;
          if (idx < (block.nodes.length - 1)) {
            html += ` <span style="font-size: 16pt;">➔</span> `;
          }
        });
        html += `
            </div>
          </div>
        `;
        break;
      default:
        break;
    }
  });

  html += `
    </body>
    </html>
  `;

  const blob = new Blob(['\ufeff' + html], { type: "application/vnd.ms-word;charset=utf-8" });
  const filename = `${title.toLowerCase().replace(/[^a-z0-9]/g, "_")}_notediq.doc`;
  downloadBlob(blob, filename);
}

// Generate PDF by building a beautiful print page and opening window.print()
export function exportToPDF(notes, title = "Study Guide") {
  const iframe = document.createElement("iframe");
  iframe.style.position = "fixed";
  iframe.style.right = "0";
  iframe.style.bottom = "0";
  iframe.style.width = "0";
  iframe.style.height = "0";
  iframe.style.border = "0";
  document.body.appendChild(iframe);

  const doc = iframe.contentWindow.document;
  doc.open();
  doc.write(`
    <html>
    <head>
      <title>${title}</title>
      <link rel="preconnect" href="https://fonts.googleapis.com">
      <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
      <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&family=Playfair+Display:ital,wght@0,700;0,900;1,700&family=Caveat:wght@400;700&display=swap" rel="stylesheet">
      <style>
        @media print {
          body { background: #fff; color: #000; padding: 20px; }
          .page-break { page-break-after: always; }
          .no-print { display: none; }
        }
        body {
          font-family: 'Inter', sans-serif;
          color: #1f2937;
          line-height: 1.6;
          padding: 40px;
          max-width: 800px;
          margin: 0 auto;
        }
        .header {
          border-bottom: 2px solid #111;
          padding-bottom: 12px;
          margin-bottom: 30px;
          display: flex;
          justify-content: space-between;
          align-items: flex-end;
        }
        .header-title {
          font-family: 'Playfair Display', serif;
          font-style: italic;
          font-size: 28px;
          font-weight: 900;
          color: #10b981;
        }
        .header-meta {
          font-size: 11px;
          text-transform: uppercase;
          letter-spacing: 0.1em;
          color: #6b7280;
        }
        .block-wrapper {
          margin-bottom: 24px;
        }
        .tag {
          font-size: 9px;
          font-weight: 700;
          letter-spacing: 0.14em;
          text-transform: uppercase;
          color: #6b7280;
          margin-bottom: 6px;
        }
        .bullet-card {
          font-family: 'Caveat', cursive;
          font-size: 18px;
          color: #1f2937;
          line-height: 1.7;
          padding-left: 10px;
        }
        .paper-card {
          background: #fffefb;
          border: 1px solid rgba(0,0,0,0.12);
          border-radius: 8px;
          padding: 14px 18px;
          box-shadow: 0 1px 3px rgba(0,0,0,0.05);
          position: relative;
        }
        .definition-term {
          font-size: 12px;
          font-weight: 700;
          letter-spacing: 0.08em;
          text-transform: uppercase;
          margin-bottom: 4px;
          font-family: 'Inter', sans-serif;
        }
        .handwriting {
          font-family: 'Caveat', cursive;
          font-size: 19px;
          color: #1f2937;
          line-height: 1.4;
        }
        .svg-container {
          text-align: center;
          margin: 10px 0;
          max-height: 250px;
        }
        .svg-container svg {
          max-width: 100%;
          height: auto;
        }
        /* Grid styling */
        .sg-grid {
          display: grid;
          grid-template-columns: 1fr 1fr;
          gap: 12px;
        }
        .sg-card {
          border: 1px solid rgba(0,0,0,0.12);
          border-radius: 8px;
          padding: 10px 12px;
          display: flex;
          gap: 8px;
          align-items: flex-start;
          background: #fff;
        }
        .sg-title {
          font-size: 11px;
          font-weight: 700;
          text-transform: uppercase;
          letter-spacing: 0.06em;
          margin-bottom: 2px;
        }
        /* Decisions and action items */
        .decision-item {
          border-left: 4px solid #94a3b8;
          background: #f8fafc;
          padding: 12px;
          border-radius: 0 8px 8px 0;
          margin-bottom: 12px;
        }
        .task-item {
          display: flex;
          gap: 10px;
          align-items: flex-start;
          background: #fff;
          border: 1px solid rgba(0,0,0,0.08);
          padding: 12px;
          border-radius: 8px;
          margin-bottom: 10px;
        }
        .task-checkbox {
          width: 16px;
          height: 16px;
          border: 1px solid #cbd5e1;
          border-radius: 4px;
          margin-top: 3px;
        }
        .task-checked {
          background-color: #3b82f6;
          border-color: #3b82f6;
        }
      </style>
    </head>
    <body>
      <div class="header">
        <div class="header-title">${title}</div>
        <div class="header-meta">NotedIQ &middot; ${new Date().toLocaleDateString()}</div>
      </div>
      <div id="content"></div>
    </body>
    </html>
  `);
  doc.close();

  const contentDiv = doc.getElementById("content");

  notes.forEach((block) => {
    const wrapper = doc.createElement("div");
    wrapper.className = "block-wrapper";

    switch (block.type) {
      case "banner-title": {
        wrapper.innerHTML = `
          <div class="tag" style="color:#1a1a1a;">✦ banner-title</div>
          <h2 style="font-family:'Playfair Display',serif; font-style:italic; font-weight:900; font-size:24px; color:#1a1a1a; text-align:center; border-bottom:1px solid #eee; padding-bottom:8px;">
            ${block.content}
          </h2>
        `;
        break;
      }
      case "bullet-list": {
        let itemsHtml = "";
        (block.items || []).forEach((item) => {
          itemsHtml += `<div><b style="color:#3b82f6;">${item.term} →</b> ${item.note}</div>`;
        });
        wrapper.innerHTML = `
          <div class="tag" style="color:#3b82f6;">– bullet-list · "${block.heading || ""}"</div>
          <div class="bullet-card">${itemsHtml}</div>
        `;
        break;
      }
      case "definition": {
        const content = block.content || "";
        const colonIdx = content.indexOf(":");
        const term = colonIdx > -1 ? content.slice(0, colonIdx).trim() : null;
        const body = colonIdx > -1 ? content.slice(colonIdx + 1).trim() : content;
        wrapper.innerHTML = `
          <div class="tag" style="color:#10b981;">◆ definition</div>
          <div class="paper-card" style="border-left: 4px solid #10b981; border-color:#10b981;">
            ${term ? `<div class="definition-term" style="color:#10b981;">${term}</div>` : ""}
            <div class="handwriting">${body}</div>
          </div>
        `;
        break;
      }
      case "example": {
        wrapper.innerHTML = `
          <div class="tag" style="color:#3b82f6;">● example</div>
          <div class="paper-card" style="border-color:rgba(59, 130, 246, 0.4);">
            <div class="handwriting">
              <span style="color:#3b82f6; font-weight:700; font-family:'Inter',sans-serif; font-size:11px; margin-right:6px;">E.G.</span>
              ${block.content}
            </div>
          </div>
        `;
        break;
      }
      case "highlight-box": {
        wrapper.innerHTML = `
          <div class="tag" style="color:#ef4444;">▲ highlight-box</div>
          <div class="paper-card" style="border: 1.5px dashed #ef4444; background:#ef444405;">
            ${block.term ? `<div class="definition-term" style="color:#ef4444;">${block.term}</div>` : ""}
            <div class="handwriting">${block.content}</div>
          </div>
        `;
        break;
      }
      case "exam-alert": {
        wrapper.innerHTML = `
          <div class="tag" style="color:#ef4444;">▲ exam-alert</div>
          <div class="paper-card" style="border: 1.5px dashed #ef4444; background:#ef444405;">
            <div class="handwriting">
              <span style="color:#ef4444; font-weight:700; font-family:'Inter',sans-serif; font-size:11px; margin-right:6px;">⚠ EXAM ALERT:</span>
              ${block.content}
            </div>
          </div>
        `;
        break;
      }
      case "note": {
        wrapper.innerHTML = `
          <div class="tag" style="color:#8b5cf6;">– note</div>
          <div class="paper-card" style="border-color:rgba(139, 92, 246, 0.3);">
            <div class="handwriting">${block.content}</div>
          </div>
        `;
        break;
      }
      case "riddle": {
        const content = block.content || "";
        const match = content.match(/\[Answer:\s*(.*?)\]/i);
        const answer = match ? match[1].trim() : null;
        const question = answer ? content.replace(/\[Answer:.*?\]/gi, "").trim() : content;
        wrapper.innerHTML = `
          <div class="tag" style="color:#f59e0b;">? riddle</div>
          <div class="paper-card" style="border-color:#f59e0b;">
            <div class="handwriting">${question}</div>
            ${answer ? `<div style="margin-top:8px; font-size:12px; color:#b45309; font-weight:600;">Answer: ${answer}</div>` : ""}
          </div>
        `;
        break;
      }
      case "decision": {
        wrapper.innerHTML = `
          <div class="decision-item">
            <div class="definition-term" style="color:#475569;">Decision</div>
            <div style="font-size:15px; font-weight:500;">${block.content}</div>
          </div>
        `;
        break;
      }
      case "task-item": {
        wrapper.innerHTML = `
          <div class="task-item">
            <div class="task-checkbox ${block.checked ? "task-checked" : ""}"></div>
            <div style="flex:1;">
              <div style="font-size:15px; font-weight:500;">${block.content}</div>
              <div style="font-size:11px; color:#6b7280; margin-top:4px;">
                @${block.assignee || "unassigned"} &middot; Priority: ${block.priority || "medium"} &middot; Due: ${block.deadline || "TBD"}
              </div>
            </div>
          </div>
        `;
        break;
      }
      case "mindmap": {
        wrapper.innerHTML = `
          <div class="tag" style="color:#10b981;">◆ mindmap · "${block.center || ""}"</div>
          <div class="svg-container" id="mm-print-container"></div>
        `;
        break;
      }
      case "flowchart": {
        wrapper.innerHTML = `
          <div class="tag" style="color:#f59e0b;">↻ flowchart · cycle · "${block.heading || "Life cycle"}"</div>
          <div class="svg-container" id="fc-print-container"></div>
        `;
        break;
      }
      case "structure-grid": {
        let itemsHtml = "";
        (block.items || []).forEach((item, idx) => {
          const colors = ["#ef4444", "#10b981", "#f59e0b", "#8b5cf6"];
          const color = colors[idx % colors.length];
          itemsHtml += `
            <div class="sg-card">
              <div>
                <div class="sg-title" style="color:${color};">${item.label}</div>
                <div class="handwriting" style="font-size:15px;">${Array.isArray(item.points) ? item.points.join(", ") : item.points}</div>
              </div>
            </div>
          `;
        });
        wrapper.innerHTML = `
          <div class="tag" style="color:#06b6d4;">▦ structure-grid</div>
          <div class="sg-grid">${itemsHtml}</div>
        `;
        break;
      }
      default:
        break;
    }

    contentDiv.appendChild(wrapper);

    if (block.type === "mindmap") {
      const mmContainer = wrapper.querySelector("#mm-print-container");
      const svgs = document.querySelectorAll("svg");
      svgs.forEach((s) => {
        if (s.querySelector(".mm-node") || s.innerHTML.includes('type="mindmap"') || s.outerHTML.includes("mm-label")) {
          const clone = s.cloneNode(true);
          clone.setAttribute("width", "360");
          clone.setAttribute("height", "270");
          clone.style.maxHeight = "200px";
          clone.style.margin = "0 auto";
          mmContainer.appendChild(clone);
        }
      });
    } else if (block.type === "flowchart") {
      const fcContainer = wrapper.querySelector("#fc-print-container");
      const svgs = document.querySelectorAll("svg");
      svgs.forEach((s) => {
        if (s.querySelector(".fc-box") || s.innerHTML.includes('type="flowchart"') || s.outerHTML.includes("fc-label")) {
          const clone = s.cloneNode(true);
          clone.setAttribute("width", "360");
          clone.setAttribute("height", "230");
          clone.style.maxHeight = "180px";
          clone.style.margin = "0 auto";
          fcContainer.appendChild(clone);
        }
      });
    }
  });

  setTimeout(() => {
    iframe.contentWindow.focus();
    iframe.contentWindow.print();
    setTimeout(() => {
      document.body.removeChild(iframe);
    }, 1000);
  }, 500);
}

// Confetti drop logic helper (pure HTML5 Canvas, zero-dependency)
export function triggerConfetti() {
  const canvas = document.createElement("canvas");
  canvas.style.position = "fixed";
  canvas.style.top = "0";
  canvas.style.left = "0";
  canvas.style.width = "100vw";
  canvas.style.height = "100vh";
  canvas.style.pointerEvents = "none";
  canvas.style.zIndex = "99999";
  document.body.appendChild(canvas);

  const ctx = canvas.getContext("2d");
  const dpr = window.devicePixelRatio || 1;
  canvas.width = window.innerWidth * dpr;
  canvas.height = window.innerHeight * dpr;

  const particles = [];
  const colors = ["#10b981", "#3b82f6", "#ef4444", "#f59e0b", "#8b5cf6", "#06b6d4"];

  for (let i = 0; i < 150; i++) {
    particles.push({
      x: Math.random() * canvas.width,
      y: -Math.random() * 200,
      r: Math.random() * 6 + 4,
      d: Math.random() * canvas.height,
      color: colors[Math.floor(Math.random() * colors.length)],
      tilt: Math.random() * 10 - 5,
      tiltAngleIncremental: Math.random() * 0.07 + 0.02,
      tiltAngle: 0,
      speed: Math.random() * 3 + 2,
    });
  }

  let animationFrameId;
  let startTime = Date.now();

  function draw() {
    ctx.clearRect(0, 0, canvas.width, canvas.height);

    let active = false;
    particles.forEach((p) => {
      p.tiltAngle += p.tiltAngleIncremental;
      p.y += p.speed;
      p.x += Math.sin(p.tiltAngle) * 0.5;
      p.tilt = Math.sin(p.tiltAngle - p.r / 2) * 5;

      if (p.y < canvas.height) {
        active = true;
      }

      ctx.beginPath();
      ctx.lineWidth = p.r;
      ctx.strokeStyle = p.color;
      ctx.moveTo(p.x + p.tilt + p.r / 2, p.y);
      ctx.lineTo(p.x + p.tilt, p.y + p.tilt + p.r / 2);
      ctx.stroke();
    });

    if (active && Date.now() - startTime < 3500) {
      animationFrameId = requestAnimationFrame(draw);
    } else {
      if (canvas.parentNode) {
        document.body.removeChild(canvas);
      }
      cancelAnimationFrame(animationFrameId);
    }
  }

  draw();
}
